version: '2'

services:
  api:
    restart: always
    build: ./projects/python
    ports:
      - "8001:8000"
    env_file: projects/python/.env

  ipfs0:
    container_name: ipfs0
    image: ipfs/kubo:release
    ports:
     - "4001:4001"
     - "5001:5001"
     - "8080:8080"
    volumes:
      - ./compose/ipfs0:/data/ipfs