// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: pubsub/pubsub.proto

package pubsub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProduceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Topic   string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *ProduceReq) Reset() {
	*x = ProduceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubsub_pubsub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceReq) ProtoMessage() {}

func (x *ProduceReq) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_pubsub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceReq.ProtoReflect.Descriptor instead.
func (*ProduceReq) Descriptor() ([]byte, []int) {
	return file_pubsub_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *ProduceReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ProduceReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ProduceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProduceRes) Reset() {
	*x = ProduceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubsub_pubsub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRes) ProtoMessage() {}

func (x *ProduceRes) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_pubsub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRes.ProtoReflect.Descriptor instead.
func (*ProduceRes) Descriptor() ([]byte, []int) {
	return file_pubsub_pubsub_proto_rawDescGZIP(), []int{1}
}

var File_pubsub_pubsub_proto protoreflect.FileDescriptor

var file_pubsub_pubsub_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x6f, 0x6e, 0x65, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x0c, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x32, 0x78, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x73, 0x75, 0x62, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x12,
	0x2c, 0x2e, 0x6f, 0x6e, 0x65, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e,
	0x6f, 0x6e, 0x65, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x49, 0x5a,
	0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x6e, 0x74,
	0x79, 0x75, 0x6b, 0x68, 0x6f, 0x76, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pubsub_pubsub_proto_rawDescOnce sync.Once
	file_pubsub_pubsub_proto_rawDescData = file_pubsub_pubsub_proto_rawDesc
)

func file_pubsub_pubsub_proto_rawDescGZIP() []byte {
	file_pubsub_pubsub_proto_rawDescOnce.Do(func() {
		file_pubsub_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(file_pubsub_pubsub_proto_rawDescData)
	})
	return file_pubsub_pubsub_proto_rawDescData
}

var file_pubsub_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pubsub_pubsub_proto_goTypes = []interface{}{
	(*ProduceReq)(nil), // 0: oneboard.public.v1.backupstorage.ProduceReq
	(*ProduceRes)(nil), // 1: oneboard.public.v1.backupstorage.ProduceRes
}
var file_pubsub_pubsub_proto_depIdxs = []int32{
	0, // 0: oneboard.public.v1.backupstorage.PubsubService.Produce:input_type -> oneboard.public.v1.backupstorage.ProduceReq
	1, // 1: oneboard.public.v1.backupstorage.PubsubService.Produce:output_type -> oneboard.public.v1.backupstorage.ProduceRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pubsub_pubsub_proto_init() }
func file_pubsub_pubsub_proto_init() {
	if File_pubsub_pubsub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pubsub_pubsub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pubsub_pubsub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pubsub_pubsub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pubsub_pubsub_proto_goTypes,
		DependencyIndexes: file_pubsub_pubsub_proto_depIdxs,
		MessageInfos:      file_pubsub_pubsub_proto_msgTypes,
	}.Build()
	File_pubsub_pubsub_proto = out.File
	file_pubsub_pubsub_proto_rawDesc = nil
	file_pubsub_pubsub_proto_goTypes = nil
	file_pubsub_pubsub_proto_depIdxs = nil
}
